# Generated by Django 5.2.7 on 2026-07-08 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحلقة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حلقة',
                'verbose_name_plural': 'الحلقات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الأستاذ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الطالب')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='halaqat.circle', verbose_name='الحلقة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='halaqat.teacher', verbose_name='الأستاذ المسؤول'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'إذن')], default='present', max_length=10, verbose_name='الحالة')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='وقت التسجيل')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='halaqat.circle', verbose_name='الحلقة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='halaqat.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
