# Generated by Django 5.2.7 on 2026-07-10 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'إذن')], default='present', max_length=10, verbose_name='الحالة')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='وقت التسجيل')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to='halaqat.circle', verbose_name='الحلقة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='halaqat.teacher', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'حضور أستاذ',
                'verbose_name_plural': 'حضور الأساتذة',
                'ordering': ['-date'],
                'unique_together': {('teacher', 'circle', 'date')},
            },
        ),
    ]
