# Generated by Django 5.2.7 on 2026-07-25 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الدورة / الدرس')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='halaqat.student', verbose_name='الطلاب المشاركون')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='halaqat.teacher', verbose_name='الأستاذ / المحاضر المسؤول')),
            ],
            options={
                'verbose_name': 'دورة / درس إضافي',
                'verbose_name_plural': 'الدورات والدروس الإضافية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'إذن')], default='present', max_length=10, verbose_name='الحالة')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='وقت التسجيل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='halaqat.course', verbose_name='الدورة / الدرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance_records', to='halaqat.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور دورة',
                'verbose_name_plural': 'سجلات حضور الدورات',
                'ordering': ['-date'],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'إذن')], default='present', max_length=10, verbose_name='الحالة')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='وقت التسجيل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to='halaqat.course', verbose_name='الدورة / الدرس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance_records', to='halaqat.teacher', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'حضور أستاذ دورة',
                'verbose_name_plural': 'حضور أساتذة الدورات',
                'ordering': ['-date'],
                'unique_together': {('teacher', 'course', 'date')},
            },
        ),
    ]
