# Generated by Django 5.2.7 on 2026-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='halaqat.teacher', verbose_name='الأساتذة / المحاضرون المسؤولون'),
        ),
    ]
