# Generated by Django 5.1.15 on 2026-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0002_remove_course_teacher_course_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['display_order', 'name', 'id'], 'verbose_name': 'حلقة', 'verbose_name_plural': 'الحلقات'},
        ),
        migrations.AddField(
            model_name='circle',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='كلما كان الرقم أصغر ظهرت الحلقة أولاً في قائمة الحلقات.', verbose_name='ترتيب العرض'),
        ),
    ]
